name: XyrqoPlugin
version: 1.0
main: de.xyrqo.plugin.XyrqoPlugin
api-version: '1.21'
author: Xyrqo
description: XyrqoSMP Plugin

commands:
  sell:
    description: Verkauft Items
    usage: /sell
  balance:
    descr
    usage: /rank <spieler> <rang>
    permission: xyrqo.rank
  unrank:
    description: Entfernt einen Rang
    usage: /unrank <spieler>
    permission: xyrqo.rank

permissions:
  xyrqo.balreset:
    default: op
  xyrqo.rank:
    default: op
